#!/usr/bin/env python3
"""Regenerate the terms file for LLM_PRIVACY_TERMS_FILE from a database — people, customers,
code names, any identity the model must never see verbatim.

    TERMS_DB_URL=postgres://...  TERMS_SQL="SELECT name, code FROM people"  \\
    TERMS_OUT=/var/lib/llm-privacy/terms.tsv  TERMS_KIND=PERSON  python3 terms-from-db.py

The query returns one row per identity: ``name`` (required) and an optional ``code`` (a personal
handle; purely numeric codes are skipped so order and SKU numbers never match). Each name expands
to the variants people actually type — "First Last", "Last First", the surname alone (4+ chars) —
and the file is written atomically, longest term first, as ``term<TAB>KIND``. Only counts are
printed; a name never reaches stdout or a log. Runs under psql; nothing else to install."""
import json
import os
import subprocess
import sys
import tempfile

OUT = os.environ.get("TERMS_OUT", "/var/lib/llm-privacy/terms.tsv")
KIND = os.environ.get("TERMS_KIND", "PERSON")
SQL = os.environ.get("TERMS_SQL", "SELECT name, code FROM people WHERE name IS NOT NULL")


def variants(name: str) -> set:
    parts = [p for p in name.split() if len(p) > 1]
    if len(parts) < 2:
        return {name.strip()} if len(name.strip()) >= 3 else set()
    first, last = parts[0], parts[-1]
    out = {" ".join(parts), " ".join(reversed(parts)), f"{first} {last}", f"{last} {first}"}
    if len(last) >= 4:
        out.add(last)
    return {v for v in out if len(v) >= 3}


def main() -> int:
    url = os.environ.get("TERMS_DB_URL") or os.environ.get("DATABASE_URL")
    if not url:
        print("TERMS_DB_URL is not set", file=sys.stderr)
        return 1
    query = f"SELECT COALESCE(json_agg(json_build_object('name', q.name, 'code', q.code)), '[]'::json) FROM ({SQL}) q"
    run = subprocess.run(["psql", url, "-At", "-v", "ON_ERROR_STOP=1", "-c", "SET statement_timeout = '30s'", "-c", query],
                         capture_output=True, text=True, timeout=120)
    if run.returncode != 0:
        print(run.stderr.strip()[:300], file=sys.stderr)
        return 1
    rows = json.loads(run.stdout.strip().splitlines()[-1] or "[]") or []
    terms = set()
    for r in rows:
        terms |= variants(str(r.get("name") or ""))
        code = str(r.get("code") or "").strip()
        if len(code) >= 4 and not code.isdigit():
            terms.add(code)
    ordered = sorted(terms, key=lambda t: (-len(t), t))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(OUT), prefix=".terms-", suffix=".tsv")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(f"# {len(ordered)} terms from {len(rows)} identities; regenerated by terms-from-db.py\n")
        for t in ordered:
            fh.write(f"{t}\t{KIND}\n")
    os.chmod(tmp, 0o644)
    os.replace(tmp, OUT)
    print(f"terms file: {len(rows)} identities -> {len(ordered)} terms -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
